# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build-and-deploy:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Use Node.js 14.x
       uses: actions/setup-node@v1
       with:
         node-version: 14.x

     - name: Prepare and deploy
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         npm install
         npm run ng -- deploy --base-href=/TicTacToe/ --name="CI/CD" --email=stefano.notaro@gmail.com
